format_version: 2
pipelines:
  "calculator-webapp":
    group: presentations-ci-cd
    materials:
      calculator-webapp:
        git: "git@github.com:Sethuraman/presentations-ci-cd-calculator-webapp.git"
    stages:
      - test:
          jobs:
            test:
              resources:
                - node
              tasks:
                - script: |
                    yarn install
                    yarn run test_with_coverage

  "deploy-calculator-webapp-staging":
    group: presentations-ci-cd
    materials:
      webapp-functional-tests-upstream:
        pipeline: calculator-functional-tests
        stage: functional-test
      webapp-checkin-upstream:
        pipeline: calculator-webapp
        stage: build
      calculator-webapp:
        git: "git@github.com:Sethuraman/presentations-ci-cd-calculator-webapp.git"  

    stages:
      - buildForStaging:
          jobs:
            build:
              resources:
                - node
              tasks:
                - script: |
                    yarn install
                    REACT_APP_API_URL="https://rnh5t2hzb3.execute-api.ap-south-1.amazonaws.com/dev" yarn run build

      - deploy:
          jobs:
            deploy:
              resources:
                - node
              tasks:
                - script: |
                     sh ./infra-cloudformation/deploy.sh staging            
              
      - sanity-check:
          jobs: 
            test:
              tasks:
                - script: |
                    echo "sanity check the web app"
                          
  "deploy-calculator-webapp-production":
    group: presentations-ci-cd
    materials:
      webapp-functional-tests-upstream:
        pipeline: deploy-calculator-webapp-staging
        stage: sanity-check
      calculator-webapp:
        git: "git@github.com:Sethuraman/presentations-ci-cd-calculator-webapp.git"  

    stages:
      - buildForProduction:
          jobs:
            build:
              resources:
                - node
              tasks:
                - script: |
                    yarn install
                    REACT_APP_API_URL="https://rnh5t2hzb3.execute-api.ap-south-1.amazonaws.com/dev" yarn run build

      - deploy:
          approval: manual
          jobs:
            deploy:
              resources:
                - node
              tasks:
                - script: |
                     sh ./infra-cloudformation/deploy.sh prod            
              
      - sanity-check:
          jobs: 
            test:
              tasks:
                - script: |
                    echo "sanity check the web app"                         

      
