format_version: 2
pipelines:
  "calculator-service":
    group: presentations-ci-cd
    materials:
      calculator-webapp:
        git: "git@github.com:Sethuraman/presentations-ci-cd-calculator-service.git"
    stages:
      - test:
          jobs:
            test:
              resources:
                - node
              tasks:
                - script: |
                    npm install
                    npm run test