format_version: 2
pipelines:
  "calculator-functional-tests":
    group: functional-tests
    materials:
      webapp-upstream:
        pipeline: unit-test-webapp
        stage: test
      service-upstream:
        pipeline: test-service
        stage: integration-test
      webapp-git:
        git: "git@github.com:Sethuraman/presentations-ci-cd-calculator-webapp.git"
        destination: webapp
      service-git:
        git: "git@github.com:Sethuraman/presentations-ci-cd-calculator-service.git"    
        destination: service
      funcational-tests-git:
        git: "git@github.com:Sethuraman/presentations-ci-cd-functional-tests.git"    
        destination: functional-tests  

    stages:
      - functional-test:
          jobs:
            test:
              resources:
                - mac
              tasks:
                - script: |
                    sh -x functional-tests/runFunctionalTests.sh