format_version: 2
pipelines:
  "unit-test-webapp":
    group: build-unit-tests
    materials:
      calculator-webapp:
        git: "git@github.com:Sethuraman/presentations-ci-cd-calculator-webapp.git"
    stages:
      - test:
          jobs:
            test:
              resources:
                - node
              tasks:
                - script: |
                    yarn install
                    yarn run test_with_coverage

  "development-deploy-webapp":
    group: deployments
    materials:
      webapp-functional-tests-upstream:
        pipeline: calculator-functional-tests
        stage: functional-test
      webapp-checkin-upstream:
        pipeline: unit-test-webapp
        stage: test
      staging-git:
        git: "git@github.com:Sethuraman/presentations-ci-cd-calculator-webapp.git"  

    stages:
      - buildForDevelopment:
          jobs:
            build:
              resources:
                - node
              tasks:
                - script: |
                    yarn install
                    REACT_APP_API_URL="https://54yymmqfpc.execute-api.ap-south-1.amazonaws.com/dev" yarn run build

      - deploy:
          jobs:
            deploy:
              resources:
                - node
              tasks:
                - script: |
                    export AWS_ACCESS_KEY_ID=$AWS_ACCESS_DEVELOPMENT_KEY
                    export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_DEVELOPMENT_KEY
                    sh ./infra-cloudformation/deploy.sh development            
              
      - sanity-check:
          jobs: 
            test:
              tasks:
                - script: |
                    echo "sanity check the web app"

  "staging-deploy-webapp":
    group: deployments
    materials:
      development-deploy-upstream:
        pipeline: development-deploy-webapp
        stage: sanity-check
      production-git:
        git: "git@github.com:Sethuraman/presentations-ci-cd-calculator-webapp.git"  

    stages:
      - buildForStaging:
          jobs:
            build:
              resources:
                - node
              tasks:
                - script: |
                    yarn install
                    REACT_APP_API_URL="https://rnh5t2hzb3.execute-api.ap-south-1.amazonaws.com/dev" yarn run build

      - deploy:
          approval: manual
          jobs:
            deploy:
              resources:
                - node
              tasks:
                - script: |
                    export AWS_ACCESS_KEY_ID=$AWS_ACCESS_STAGING_KEY
                    export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_STAGING_KEY
                    sh ./infra-cloudformation/deploy.sh staging            
              
      - sanity-check:
          jobs: 
            test:
              tasks:
                - script: |
                    echo "sanity check the web app"                  
                          
  "prod-deploy-webapp":
    group: deployments
    materials:
      staging-deploy-upstream:
        pipeline: staging-deploy-webapp
        stage: sanity-check
      production-git:
        git: "git@github.com:Sethuraman/presentations-ci-cd-calculator-webapp.git"  

    stages:
      - buildForProduction:
          jobs:
            build:
              resources:
                - node
              tasks:
                - script: |
                    yarn install
                    REACT_APP_API_URL="https://y4ijbwtqp8.execute-api.ap-south-1.amazonaws.com/dev" yarn run build

      - deploy:
          approval: manual
          jobs:
            deploy:
              resources:
                - node
              tasks:
                - script: |
                     export AWS_ACCESS_KEY_ID=$AWS_ACCESS_PRODUCTION_KEY
                     export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_PRODUCTION_KEY
                     sh ./infra-cloudformation/deploy.sh prod            
              
      - sanity-check:
          jobs: 
            test:
              tasks:
                - script: |
                    echo "sanity check the web app"                         

      
