format_version: 2
pipelines:
  "calculator-functional-tests":
    group: presentations-ci-cd
    materials:
      webapp-upstream:
        pipeline: unit-test-webapp
        stage: test
      service-upstream:
        pipeline: test-service
        stage: integration-test
      webapp-git:
        git: "git@github.com:Sethuraman/presentations-ci-cd-calculator-webapp.git"
        destination: webapp
      service-git:
        git: "git@github.com:Sethuraman/presentations-ci-cd-calculator-service.git"    
        destination: service

    stages:
      - functional-test:
          jobs:
            test:
              resources:
                - node
              tasks:
                - script: |
                    pwd
                    echo "run functional test here"
                    ls