format_version: 2
pipelines:
  "calculator-webapp":
    group: presentations-ci-cd
    materials:
      calculator-webapp:
        git: "git@github.com:Sethuraman/presentations-ci-cd-calculator-webapp.git"
    stages:
      - test:
          jobs:
            test:
              resources:
                - node
              tasks:
                - script: |
                    yarn install
                    yarn run test_with_coverage
      - build:
          jobs:
            build:
              artifacts:
                - build:
                    source: build
                    destination: dist
              resources:
                - node
              tasks:
                - script: |
                    yarn install
                    yarn run build

  "deploy-calculator-webapp-staging":
    group: presentations-ci-cd
      materials:
        webapp-functional-tests-upstream:
          pipeline: calculator-functional-tests
          stage: functional-test

    stages:
      - deploy:
          jobs:
            deploy:
              tasks:
                - fetch:
                    pipeline: calculator-webapp
                    stage: build
                    job: build
                    is_file: false
                    source: dist
                    destination: dist
                - script: |
                    ls dist    

      
