format_version: 2
pipelines:
  "calculator-functional-tests":
    group: presentations-ci-cd
    materials:
      webapp-upstream:
        pipeline: unit-test-webapp
        stage: test
      service-upstream:
        pipeline: test-service
        stage: integration-test

    stages:
      - functional-test:
          jobs:
            test:
              resources:
                - node
              tasks:
                - script: |
                    echo "run functional test here"