format_version: 2
environments:
  ci:
    pipelines:
      - "test-service"
      - "staging-deploy-service"
      - "development-deploy-service"
      - "production-deploy-service"
      - "unit-test-webapp"
      - "staging-deploy-webapp"
      - "development-deploy-webapp"
      - "prod-deploy-webapp"
      - "calculator-functional-tests"
    
