format_version: 2
environments:
  ci:
    pipelines:
      - "calculator-webapp"
      - "calculator-service"
      - "calculator-functional-tests"
      - "deploy-calculator-webapp-staging"
      - "deploy-calculator-webapp-production"
      - "deploy-calculator-service-staging"
      - "deploy-calculator-service-production"
